.TH GW-MONITOR 8 "08 Sep 2017" "gw-monitor"
.SH NAME
gw-monitor \- Default Gateway Monitor
.SH SYNOPSIS
.B gw-monitor
.I INTERFACE
.SH DESCRIPTION
.B gw-monitor
monitors the routing table and checks if the default route points to
a specified interface.
.SH OPTIONS
.TP
.BR -h ", " --help
Show help message and exit.
.SH BUGS
No known bugs.
